name: fluttertalk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_chat_ui: ^1.6.8
  flutter_chat_types: ^3.6.2
  flutter_chat_core: ^2.4.0
  image_picker: ^0.8.7+5
  uuid: ^4.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
